/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.ndk_demo_lib;

public class SwigDemoJNI {
  public final static native long new_StringVector__SWIG_0();
  public final static native long new_StringVector__SWIG_1(long jarg1, StringVector jarg1_);
  public final static native boolean StringVector_isEmpty(long jarg1, StringVector jarg1_);
  public final static native void StringVector_clear(long jarg1, StringVector jarg1_);
  public final static native long new_StringVector__SWIG_2(int jarg1, String jarg2);
  public final static native int StringVector_doCapacity(long jarg1, StringVector jarg1_);
  public final static native void StringVector_doReserve(long jarg1, StringVector jarg1_, int jarg2);
  public final static native int StringVector_doSize(long jarg1, StringVector jarg1_);
  public final static native void StringVector_doAdd__SWIG_0(long jarg1, StringVector jarg1_, String jarg2);
  public final static native void StringVector_doAdd__SWIG_1(long jarg1, StringVector jarg1_, int jarg2, String jarg3);
  public final static native String StringVector_doRemove(long jarg1, StringVector jarg1_, int jarg2);
  public final static native String StringVector_doGet(long jarg1, StringVector jarg1_, int jarg2);
  public final static native String StringVector_doSet(long jarg1, StringVector jarg1_, int jarg2, String jarg3);
  public final static native void StringVector_doRemoveRange(long jarg1, StringVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_StringVector(long jarg1);
  public final static native long new_IntVector__SWIG_0();
  public final static native long new_IntVector__SWIG_1(long jarg1, IntVector jarg1_);
  public final static native boolean IntVector_isEmpty(long jarg1, IntVector jarg1_);
  public final static native void IntVector_clear(long jarg1, IntVector jarg1_);
  public final static native long new_IntVector__SWIG_2(int jarg1, int jarg2);
  public final static native int IntVector_doCapacity(long jarg1, IntVector jarg1_);
  public final static native void IntVector_doReserve(long jarg1, IntVector jarg1_, int jarg2);
  public final static native int IntVector_doSize(long jarg1, IntVector jarg1_);
  public final static native void IntVector_doAdd__SWIG_0(long jarg1, IntVector jarg1_, int jarg2);
  public final static native void IntVector_doAdd__SWIG_1(long jarg1, IntVector jarg1_, int jarg2, int jarg3);
  public final static native int IntVector_doRemove(long jarg1, IntVector jarg1_, int jarg2);
  public final static native int IntVector_doGet(long jarg1, IntVector jarg1_, int jarg2);
  public final static native int IntVector_doSet(long jarg1, IntVector jarg1_, int jarg2, int jarg3);
  public final static native void IntVector_doRemoveRange(long jarg1, IntVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_IntVector(long jarg1);
  public final static native long new_TestSwigData2Vector__SWIG_0();
  public final static native long new_TestSwigData2Vector__SWIG_1(long jarg1, TestSwigData2Vector jarg1_);
  public final static native boolean TestSwigData2Vector_isEmpty(long jarg1, TestSwigData2Vector jarg1_);
  public final static native void TestSwigData2Vector_clear(long jarg1, TestSwigData2Vector jarg1_);
  public final static native long new_TestSwigData2Vector__SWIG_2(int jarg1, long jarg2, TestSwigData2 jarg2_);
  public final static native int TestSwigData2Vector_doCapacity(long jarg1, TestSwigData2Vector jarg1_);
  public final static native void TestSwigData2Vector_doReserve(long jarg1, TestSwigData2Vector jarg1_, int jarg2);
  public final static native int TestSwigData2Vector_doSize(long jarg1, TestSwigData2Vector jarg1_);
  public final static native void TestSwigData2Vector_doAdd__SWIG_0(long jarg1, TestSwigData2Vector jarg1_, long jarg2, TestSwigData2 jarg2_);
  public final static native void TestSwigData2Vector_doAdd__SWIG_1(long jarg1, TestSwigData2Vector jarg1_, int jarg2, long jarg3, TestSwigData2 jarg3_);
  public final static native long TestSwigData2Vector_doRemove(long jarg1, TestSwigData2Vector jarg1_, int jarg2);
  public final static native long TestSwigData2Vector_doGet(long jarg1, TestSwigData2Vector jarg1_, int jarg2);
  public final static native long TestSwigData2Vector_doSet(long jarg1, TestSwigData2Vector jarg1_, int jarg2, long jarg3, TestSwigData2 jarg3_);
  public final static native void TestSwigData2Vector_doRemoveRange(long jarg1, TestSwigData2Vector jarg1_, int jarg2, int jarg3);
  public final static native void delete_TestSwigData2Vector(long jarg1);
  public final static native void TestSwigData2_value1_set(long jarg1, TestSwigData2 jarg1_, int jarg2);
  public final static native int TestSwigData2_value1_get(long jarg1, TestSwigData2 jarg1_);
  public final static native void TestSwigData2_value2_set(long jarg1, TestSwigData2 jarg1_, long jarg2);
  public final static native long TestSwigData2_value2_get(long jarg1, TestSwigData2 jarg1_);
  public final static native void TestSwigData2_value3_set(long jarg1, TestSwigData2 jarg1_, int jarg2);
  public final static native int TestSwigData2_value3_get(long jarg1, TestSwigData2 jarg1_);
  public final static native void TestSwigData2_value4_set(long jarg1, TestSwigData2 jarg1_, long jarg2);
  public final static native long TestSwigData2_value4_get(long jarg1, TestSwigData2 jarg1_);
  public final static native void TestSwigData2_value5_set(long jarg1, TestSwigData2 jarg1_, float jarg2);
  public final static native float TestSwigData2_value5_get(long jarg1, TestSwigData2 jarg1_);
  public final static native void TestSwigData2_value6_set(long jarg1, TestSwigData2 jarg1_, double jarg2);
  public final static native double TestSwigData2_value6_get(long jarg1, TestSwigData2 jarg1_);
  public final static native void TestSwigData2_value7_set(long jarg1, TestSwigData2 jarg1_, String jarg2);
  public final static native String TestSwigData2_value7_get(long jarg1, TestSwigData2 jarg1_);
  public final static native long new_TestSwigData2();
  public final static native void delete_TestSwigData2(long jarg1);
  public final static native void TestSwigData_value1_set(long jarg1, TestSwigData jarg1_, int jarg2);
  public final static native int TestSwigData_value1_get(long jarg1, TestSwigData jarg1_);
  public final static native void TestSwigData_value2_set(long jarg1, TestSwigData jarg1_, long jarg2);
  public final static native long TestSwigData_value2_get(long jarg1, TestSwigData jarg1_);
  public final static native void TestSwigData_value3_set(long jarg1, TestSwigData jarg1_, int jarg2);
  public final static native int TestSwigData_value3_get(long jarg1, TestSwigData jarg1_);
  public final static native void TestSwigData_value4_set(long jarg1, TestSwigData jarg1_, long jarg2);
  public final static native long TestSwigData_value4_get(long jarg1, TestSwigData jarg1_);
  public final static native void TestSwigData_value5_set(long jarg1, TestSwigData jarg1_, float jarg2);
  public final static native float TestSwigData_value5_get(long jarg1, TestSwigData jarg1_);
  public final static native void TestSwigData_value6_set(long jarg1, TestSwigData jarg1_, double jarg2);
  public final static native double TestSwigData_value6_get(long jarg1, TestSwigData jarg1_);
  public final static native void TestSwigData_value7_set(long jarg1, TestSwigData jarg1_, String jarg2);
  public final static native String TestSwigData_value7_get(long jarg1, TestSwigData jarg1_);
  public final static native void TestSwigData_values1_set(long jarg1, TestSwigData jarg1_, long jarg2, IntVector jarg2_);
  public final static native long TestSwigData_values1_get(long jarg1, TestSwigData jarg1_);
  public final static native void TestSwigData_values2_set(long jarg1, TestSwigData jarg1_, long jarg2, StringVector jarg2_);
  public final static native long TestSwigData_values2_get(long jarg1, TestSwigData jarg1_);
  public final static native void TestSwigData_values3_set(long jarg1, TestSwigData jarg1_, long jarg2, TestSwigData2Vector jarg2_);
  public final static native long TestSwigData_values3_get(long jarg1, TestSwigData jarg1_);
  public final static native long new_TestSwigData();
  public final static native void delete_TestSwigData(long jarg1);
  public final static native long new_TestSwig__SWIG_0();
  public final static native long new_TestSwig__SWIG_1(double jarg1);
  public final static native double TestSwig_Area(long jarg1, TestSwig jarg1_);
  public final static native void TestSwig_test1(long jarg1, TestSwig jarg1_, long jarg2, TestSwigData jarg2_);
  public final static native void TestSwig_test2(long jarg1, TestSwig jarg1_, long jarg2, TestCallbackWrapper jarg2_);
  public final static native void delete_TestSwig(long jarg1);
  public final static native void delete_TestCallbackWrapper(long jarg1);
  public final static native void TestCallbackWrapper_call(long jarg1, TestCallbackWrapper jarg1_, long jarg2, TestSwigData jarg2_);
  public final static native long new_TestCallbackWrapper();
  public final static native void TestCallbackWrapper_director_connect(TestCallbackWrapper obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void TestCallbackWrapper_change_ownership(TestCallbackWrapper obj, long cptr, boolean take_or_release);
  public final static native void testCallbackAdapter(long jarg1, TestSwig jarg1_, long jarg2, TestCallbackWrapper jarg2_);

  public static void SwigDirector_TestCallbackWrapper_call(TestCallbackWrapper jself, long value) {
    jself.call(new TestSwigData(value, false));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
