/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.ndk_demo_lib;

public class SWIGDemoJNI {
  public final static native void TestCallback_onTest(long jarg1, TestCallback jarg1_, double jarg2);
  public final static native void delete_TestCallback(long jarg1);
  public final static native long new_TestSwig__SWIG_0();
  public final static native long new_TestSwig__SWIG_1(double jarg1);
  public final static native double TestSwig_Area(long jarg1, TestSwig jarg1_);
  public final static native void TestSwig_testCallback(long jarg1, TestSwig jarg1_, long jarg2, TestCallback jarg2_);
  public final static native void delete_TestSwig(long jarg1);
}
