/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.ndk_demo_lib;

public class SwigDemo {
  public static void testCallbackAdapter(TestSwig self, TestCallbackWrapper wrapper) {
    SwigDemoJNI.testCallbackAdapter(TestSwig.getCPtr(self), self, TestCallbackWrapper.getCPtr(wrapper), wrapper);
  }

}
