/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.ndk_demo_lib;

public class TestSwig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TestSwig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TestSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TestSwig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SWIGDemoJNI.delete_TestSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TestSwig() {
    this(SWIGDemoJNI.new_TestSwig__SWIG_0(), true);
  }

  public TestSwig(double R) {
    this(SWIGDemoJNI.new_TestSwig__SWIG_1(R), true);
  }

  public double Area() {
    return SWIGDemoJNI.TestSwig_Area(swigCPtr, this);
  }

  public void testCallback(TestCallback callback) {
    SWIGDemoJNI.TestSwig_testCallback(swigCPtr, this, TestCallback.getCPtr(callback), callback);
  }

}
