/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.ndk_demo_lib;

public class TestSwigData2Vector extends java.util.AbstractList<TestSwigData2> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TestSwigData2Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TestSwigData2Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TestSwigData2Vector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigDemoJNI.delete_TestSwigData2Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TestSwigData2Vector(TestSwigData2[] initialElements) {
    this();
    reserve(initialElements.length);

    for (TestSwigData2 element : initialElements) {
      add(element);
    }
  }

  public TestSwigData2Vector(Iterable<TestSwigData2> initialElements) {
    this();
    for (TestSwigData2 element : initialElements) {
      add(element);
    }
  }

  public TestSwigData2 get(int index) {
    return doGet(index);
  }

  public TestSwigData2 set(int index, TestSwigData2 e) {
    return doSet(index, e);
  }

  public boolean add(TestSwigData2 e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, TestSwigData2 e) {
    modCount++;
    doAdd(index, e);
  }

  public TestSwigData2 remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public TestSwigData2Vector() {
    this(SwigDemoJNI.new_TestSwigData2Vector__SWIG_0(), true);
  }

  public TestSwigData2Vector(TestSwigData2Vector other) {
    this(SwigDemoJNI.new_TestSwigData2Vector__SWIG_1(TestSwigData2Vector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return SwigDemoJNI.TestSwigData2Vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SwigDemoJNI.TestSwigData2Vector_clear(swigCPtr, this);
  }

  public TestSwigData2Vector(int count, TestSwigData2 value) {
    this(SwigDemoJNI.new_TestSwigData2Vector__SWIG_2(count, TestSwigData2.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return SwigDemoJNI.TestSwigData2Vector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    SwigDemoJNI.TestSwigData2Vector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return SwigDemoJNI.TestSwigData2Vector_doSize(swigCPtr, this);
  }

  private void doAdd(TestSwigData2 x) {
    SwigDemoJNI.TestSwigData2Vector_doAdd__SWIG_0(swigCPtr, this, TestSwigData2.getCPtr(x), x);
  }

  private void doAdd(int index, TestSwigData2 x) {
    SwigDemoJNI.TestSwigData2Vector_doAdd__SWIG_1(swigCPtr, this, index, TestSwigData2.getCPtr(x), x);
  }

  private TestSwigData2 doRemove(int index) {
    return new TestSwigData2(SwigDemoJNI.TestSwigData2Vector_doRemove(swigCPtr, this, index), true);
  }

  private TestSwigData2 doGet(int index) {
    return new TestSwigData2(SwigDemoJNI.TestSwigData2Vector_doGet(swigCPtr, this, index), false);
  }

  private TestSwigData2 doSet(int index, TestSwigData2 val) {
    return new TestSwigData2(SwigDemoJNI.TestSwigData2Vector_doSet(swigCPtr, this, index, TestSwigData2.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    SwigDemoJNI.TestSwigData2Vector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
